### ISSUE TITLE
script fails with sh: 1: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by nagaisa** [EMLommers/Apollolake_Audio#4]
full output:

```
sudo sh /home/user/Apollolake_Audio/apollolake_audio2.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'alsa-topology-conf' for glob 'alsa-topology*'
Note, selecting 'alsa-ucm-conf' for glob 'alsa-ucm*'
alsa-topology-conf is already the newest version (1.2.2-1).
alsa-ucm-conf is already the newest version (1.2.2-1ubuntu0.13).
linux-firmware is already the newest version (20220329.git681281e4-0ubuntu1+system76~1648845229~20.04~f573d5b).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
sh: 1: Syntax error: Unterminated quoted string
```

**Comment by nagaisa** [comment]
from what i tested 
`sudo sh -c 'echo "options snd-sof-pci fw_path="intel/sof" >>  /etc/modprobe.d/inteldsp.conf'`
is the one causeing the isuse

**Comment by EMLommers** [comment]
Add before the quotation marks of "intel/sof".. \
Results is:
$ sudo sh -c 'echo "options snd-sof-pci fw_path=\"intel/sof\" >>  /etc/modprobe.d/inteldsp.conf'

Check software path via journalctl and adjust accordingly

**Comment by EMLommers** [comment]
Or create a file in /etc/modprobe.d   for example sofpath.conf
contents of the file:
options snd-sof-pci fw_path="intel/sof"

**Comment by EMLommers** [comment]
should be ok now

**Comment by Meganium97** [comment]
Should be properly fixed now.

**Comment by EMLommers** [comment]
Fixed
